-   name: Install CUPS
    become: yes
    apt: pkg=cups state=latest

-   name: Install printers
    become: yes
    command: "lpadmin -p {{item.name }} -v {{ item.uri }} -E -m drv:///sample.drv/zebra.ppd"
    with_items: "{{ printers }}"

-   name: Configure media types
    become: yes
    command: "lpoptions -p {{ item.name }} -o media={{ item.media }}"
    with_items: "{{ printers }}"

-   name: Confirgure printer DPIs
    become: yes
    command: "lpoptions -p {{ item.name }} -o Resolution={{ item.dpi }}"
    with_items: "{{ printers }}"