-   name: "Install php{{ php_version }}"
    become: yes
    apt: pkg="php{{ php_version }}" state=latest

-   name: Setup php.ini
    become: yes
    lineinfile: dest="/etc/php/{{ php_version }}/apache2/php.ini"
                regexp="{{ item.reg }}"
                line="{{ item.line }}"
    with_items: "{{ php_ini_settings }}"
    